### PR TITLE
curved velocity

### PR DESCRIPTION
**Pull request by Sceptus**
it done, just needs bug-fixing maybe and testing and tuning

### CODE REVIEW

**Review by mridhanbalaji — CHANGES_REQUESTED** [review]
Lines 57 to 58, why do you divide by 100?

Also lines 54 and 55 no need to limit to 127 to negative 127 since you are doing desired power right. Create a constant variable which will be the maximum voltage output of the vex v5 motor, then divide it by 127 to get percentage, then multiply by the max voltage to get the actual desired power output of the motor. 

const maxvolt = //Search up online
((controllerY + controllerX)/127)*maxvolt

then for your bounding statements limit with he maxvolt.

**Review by mridhanbalaji — APPROVED** [review]
ok.

**Comment by mridhanbalaji** [comment]
ok.

**Comment by Sceptus** [comment]
wait your right

**Comment by Sceptus** [comment]
no need to limit and no need to convert it either since .get_analog() already outputs on a range from -127 to 127

**Pull request merged**
